title: Git Justins Page
author: eEqualsMxC
email: justinmustaine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first website and in time I will frequently update in time.

# social links
twitter_username: N/A
github_username: eEqualsMxC 

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
